import type { CountryCode } from "@/components/form/group-input/PhoneInput";

export const ALL_COUNTRIES: CountryCode[] = [
  { code: "AF", name: "Afghanistan", label: "+93" },
  { code: "AL", name: "Albania", label: "+355" },
  { code: "DZ", name: "Algeria", label: "+213" },
  { code: "AS", name: "American Samoa", label: "+1684" },
  { code: "AD", name: "Andorra", label: "+376" },
  { code: "AO", name: "Angola", label: "+244" },
  { code: "AI", name: "Anguilla", label: "+1264" },
  { code: "AG", name: "Antigua and Barbuda", label: "+1268" },
  { code: "AR", name: "Argentina", label: "+54" },
  { code: "AM", name: "Armenia", label: "+374" },
  { code: "AW", name: "Aruba", label: "+297" },
  { code: "AU", name: "Australia", label: "+61" },
  { code: "AT", name: "Austria", label: "+43" },
  { code: "AZ", name: "Azerbaijan", label: "+994" },
  { code: "BS", name: "Bahamas", label: "+1242" },
  { code: "BH", name: "Bahrain", label: "+973" },
  { code: "BD", name: "Bangladesh", label: "+880" },
  { code: "BB", name: "Barbados", label: "+1246" },
  { code: "BY", name: "Belarus", label: "+375" },
  { code: "BE", name: "Belgium", label: "+32" },
  { code: "BZ", name: "Belize", label: "+501" },
  { code: "BJ", name: "Benin", label: "+229" },
  { code: "BM", name: "Bermuda", label: "+1441" },
  { code: "BT", name: "Bhutan", label: "+975" },
  { code: "BO", name: "Bolivia", label: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", label: "+387" },
  { code: "BW", name: "Botswana", label: "+267" },
  { code: "BR", name: "Brazil", label: "+55" },
  { code: "VG", name: "British Virgin Islands", label: "+1284" },
  { code: "BN", name: "Brunei", label: "+673" },
  { code: "BG", name: "Bulgaria", label: "+359" },
  { code: "BF", name: "Burkina Faso", label: "+226" },
  { code: "BI", name: "Burundi", label: "+257" },
  { code: "KH", name: "Cambodia", label: "+855" },
  { code: "CM", name: "Cameroon", label: "+237" },
  { code: "CA", name: "Canada", label: "+1" },
  { code: "CV", name: "Cape Verde", label: "+238" },
  { code: "KY", name: "Cayman Islands", label: "+1345" },
  { code: "CF", name: "Central African Republic", label: "+236" },
  { code: "TD", name: "Chad", label: "+235" },
  { code: "CL", name: "Chile", label: "+56" },
  { code: "CN", name: "China", label: "+86" },
  { code: "CO", name: "Colombia", label: "+57" },
  { code: "KM", name: "Comoros", label: "+269" },
  { code: "CD", name: "Congo (DRC)", label: "+243" },
  { code: "CG", name: "Congo (Republic)", label: "+242" },
  { code: "CK", name: "Cook Islands", label: "+682" },
  { code: "CR", name: "Costa Rica", label: "+506" },
  { code: "HR", name: "Croatia", label: "+385" },
  { code: "CU", name: "Cuba", label: "+53" },
  { code: "CW", name: "Curaçao", label: "+599" },
  { code: "CY", name: "Cyprus", label: "+357" },
  { code: "CZ", name: "Czech Republic", label: "+420" },
  { code: "DK", name: "Denmark", label: "+45" },
  { code: "DJ", name: "Djibouti", label: "+253" },
  { code: "DM", name: "Dominica", label: "+1767" },
  { code: "DO", name: "Dominican Republic", label: "+1809" },
  { code: "EC", name: "Ecuador", label: "+593" },
  { code: "EG", name: "Egypt", label: "+20" },
  { code: "SV", name: "El Salvador", label: "+503" },
  { code: "GQ", name: "Equatorial Guinea", label: "+240" },
  { code: "ER", name: "Eritrea", label: "+291" },
  { code: "EE", name: "Estonia", label: "+372" },
  { code: "SZ", name: "Eswatini", label: "+268" },
  { code: "ET", name: "Ethiopia", label: "+251" },
  { code: "FK", name: "Falkland Islands", label: "+500" },
  { code: "FO", name: "Faroe Islands", label: "+298" },
  { code: "FJ", name: "Fiji", label: "+679" },
  { code: "FI", name: "Finland", label: "+358" },
  { code: "FR", name: "France", label: "+33" },
  { code: "GF", name: "French Guiana", label: "+594" },
  { code: "PF", name: "French Polynesia", label: "+689" },
  { code: "GA", name: "Gabon", label: "+241" },
  { code: "GM", name: "Gambia", label: "+220" },
  { code: "GE", name: "Georgia", label: "+995" },
  { code: "DE", name: "Germany", label: "+49" },
  { code: "GH", name: "Ghana", label: "+233" },
  { code: "GI", name: "Gibraltar", label: "+350" },
  { code: "GR", name: "Greece", label: "+30" },
  { code: "GL", name: "Greenland", label: "+299" },
  { code: "GD", name: "Grenada", label: "+1473" },
  { code: "GP", name: "Guadeloupe", label: "+590" },
  { code: "GU", name: "Guam", label: "+1671" },
  { code: "GT", name: "Guatemala", label: "+502" },
  { code: "GN", name: "Guinea", label: "+224" },
  { code: "GW", name: "Guinea-Bissau", label: "+245" },
  { code: "GY", name: "Guyana", label: "+592" },
  { code: "HT", name: "Haiti", label: "+509" },
  { code: "HN", name: "Honduras", label: "+504" },
  { code: "HK", name: "Hong Kong", label: "+852" },
  { code: "HU", name: "Hungary", label: "+36" },
  { code: "IS", name: "Iceland", label: "+354" },
  { code: "IN", name: "India", label: "+91" },
  { code: "ID", name: "Indonesia", label: "+62" },
  { code: "IR", name: "Iran", label: "+98" },
  { code: "IQ", name: "Iraq", label: "+964" },
  { code: "IE", name: "Ireland", label: "+353" },
  { code: "IM", name: "Isle of Man", label: "+44" },
  { code: "IL", name: "Israel", label: "+972" },
  { code: "IT", name: "Italy", label: "+39" },
  { code: "JM", name: "Jamaica", label: "+1876" },
  { code: "JP", name: "Japan", label: "+81" },
  { code: "JE", name: "Jersey", label: "+44" },
  { code: "JO", name: "Jordan", label: "+962" },
  { code: "KZ", name: "Kazakhstan", label: "+7" },
  { code: "KE", name: "Kenya", label: "+254" },
  { code: "KI", name: "Kiribati", label: "+686" },
  { code: "KW", name: "Kuwait", label: "+965" },
  { code: "KG", name: "Kyrgyzstan", label: "+996" },
  { code: "LA", name: "Laos", label: "+856" },
  { code: "LV", name: "Latvia", label: "+371" },
  { code: "LB", name: "Lebanon", label: "+961" },
  { code: "LS", name: "Lesotho", label: "+266" },
  { code: "LR", name: "Liberia", label: "+231" },
  { code: "LY", name: "Libya", label: "+218" },
  { code: "LI", name: "Liechtenstein", label: "+423" },
  { code: "LT", name: "Lithuania", label: "+370" },
  { code: "LU", name: "Luxembourg", label: "+352" },
  { code: "MO", name: "Macau", label: "+853" },
  { code: "MG", name: "Madagascar", label: "+261" },
  { code: "MW", name: "Malawi", label: "+265" },
  { code: "MY", name: "Malaysia", label: "+60" },
  { code: "MV", name: "Maldives", label: "+960" },
  { code: "ML", name: "Mali", label: "+223" },
  { code: "MT", name: "Malta", label: "+356" },
  { code: "MH", name: "Marshall Islands", label: "+692" },
  { code: "MQ", name: "Martinique", label: "+596" },
  { code: "MR", name: "Mauritania", label: "+222" },
  { code: "MU", name: "Mauritius", label: "+230" },
  { code: "YT", name: "Mayotte", label: "+262" },
  { code: "MX", name: "Mexico", label: "+52" },
  { code: "FM", name: "Micronesia", label: "+691" },
  { code: "MD", name: "Moldova", label: "+373" },
  { code: "MC", name: "Monaco", label: "+377" },
  { code: "MN", name: "Mongolia", label: "+976" },
  { code: "ME", name: "Montenegro", label: "+382" },
  { code: "MS", name: "Montserrat", label: "+1664" },
  { code: "MA", name: "Morocco", label: "+212" },
  { code: "MZ", name: "Mozambique", label: "+258" },
  { code: "MM", name: "Myanmar", label: "+95" },
  { code: "NA", name: "Namibia", label: "+264" },
  { code: "NR", name: "Nauru", label: "+674" },
  { code: "NP", name: "Nepal", label: "+977" },
  { code: "NL", name: "Netherlands", label: "+31" },
  { code: "NC", name: "New Caledonia", label: "+687" },
  { code: "NZ", name: "New Zealand", label: "+64" },
  { code: "NI", name: "Nicaragua", label: "+505" },
  { code: "NE", name: "Niger", label: "+227" },
  { code: "NG", name: "Nigeria", label: "+234" },
  { code: "NU", name: "Niue", label: "+683" },
  { code: "KP", name: "North Korea", label: "+850" },
  { code: "MK", name: "North Macedonia", label: "+389" },
  { code: "MP", name: "Northern Mariana Islands", label: "+1670" },
  { code: "NO", name: "Norway", label: "+47" },
  { code: "OM", name: "Oman", label: "+968" },
  { code: "PK", name: "Pakistan", label: "+92" },
  { code: "PW", name: "Palau", label: "+680" },
  { code: "PS", name: "Palestine", label: "+970" },
  { code: "PA", name: "Panama", label: "+507" },
  { code: "PG", name: "Papua New Guinea", label: "+675" },
  { code: "PY", name: "Paraguay", label: "+595" },
  { code: "PE", name: "Peru", label: "+51" },
  { code: "PH", name: "Philippines", label: "+63" },
  { code: "PL", name: "Poland", label: "+48" },
  { code: "PT", name: "Portugal", label: "+351" },
  { code: "PR", name: "Puerto Rico", label: "+1787" },
  { code: "QA", name: "Qatar", label: "+974" },
  { code: "RE", name: "Réunion", label: "+262" },
  { code: "RO", name: "Romania", label: "+40" },
  { code: "RU", name: "Russia", label: "+7" },
  { code: "RW", name: "Rwanda", label: "+250" },
  { code: "SH", name: "Saint Helena", label: "+290" },
  { code: "KN", name: "Saint Kitts and Nevis", label: "+1869" },
  { code: "LC", name: "Saint Lucia", label: "+1758" },
  { code: "PM", name: "Saint Pierre and Miquelon", label: "+508" },
  { code: "VC", name: "Saint Vincent and the Grenadines", label: "+1784" },
  { code: "WS", name: "Samoa", label: "+685" },
  { code: "SM", name: "San Marino", label: "+378" },
  { code: "ST", name: "São Tomé and Príncipe", label: "+239" },
  { code: "SA", name: "Saudi Arabia", label: "+966" },
  { code: "SN", name: "Senegal", label: "+221" },
  { code: "RS", name: "Serbia", label: "+381" },
  { code: "SC", name: "Seychelles", label: "+248" },
  { code: "SL", name: "Sierra Leone", label: "+232" },
  { code: "SG", name: "Singapore", label: "+65" },
  { code: "SK", name: "Slovakia", label: "+421" },
  { code: "SI", name: "Slovenia", label: "+386" },
  { code: "SB", name: "Solomon Islands", label: "+677" },
  { code: "SO", name: "Somalia", label: "+252" },
  { code: "ZA", name: "South Africa", label: "+27" },
  { code: "KR", name: "South Korea", label: "+82" },
  { code: "SS", name: "South Sudan", label: "+211" },
  { code: "ES", name: "Spain", label: "+34" },
  { code: "LK", name: "Sri Lanka", label: "+94" },
  { code: "SD", name: "Sudan", label: "+249" },
  { code: "SR", name: "Suriname", label: "+597" },
  { code: "SE", name: "Sweden", label: "+46" },
  { code: "CH", name: "Switzerland", label: "+41" },
  { code: "SY", name: "Syria", label: "+963" },
  { code: "TW", name: "Taiwan", label: "+886" },
  { code: "TJ", name: "Tajikistan", label: "+992" },
  { code: "TZ", name: "Tanzania", label: "+255" },
  { code: "TH", name: "Thailand", label: "+66" },
  { code: "TL", name: "Timor-Leste", label: "+670" },
  { code: "TG", name: "Togo", label: "+228" },
  { code: "TK", name: "Tokelau", label: "+690" },
  { code: "TO", name: "Tonga", label: "+676" },
  { code: "TT", name: "Trinidad and Tobago", label: "+1868" },
  { code: "TN", name: "Tunisia", label: "+216" },
  { code: "TR", name: "Turkey", label: "+90" },
  { code: "TM", name: "Turkmenistan", label: "+993" },
  { code: "TC", name: "Turks and Caicos Islands", label: "+1649" },
  { code: "TV", name: "Tuvalu", label: "+688" },
  { code: "UG", name: "Uganda", label: "+256" },
  { code: "UA", name: "Ukraine", label: "+380" },
  { code: "AE", name: "United Arab Emirates", label: "+971" },
  { code: "GB", name: "United Kingdom", label: "+44" },
  { code: "US", name: "United States", label: "+1" },
  { code: "UY", name: "Uruguay", label: "+598" },
  { code: "UZ", name: "Uzbekistan", label: "+998" },
  { code: "VU", name: "Vanuatu", label: "+678" },
  { code: "VA", name: "Vatican City", label: "+39" },
  { code: "VE", name: "Venezuela", label: "+58" },
  { code: "VN", name: "Vietnam", label: "+84" },
  { code: "WF", name: "Wallis and Futuna", label: "+681" },
  { code: "YE", name: "Yemen", label: "+967" },
  { code: "ZM", name: "Zambia", label: "+260" },
  { code: "ZW", name: "Zimbabwe", label: "+263" }
];
